import Foundation

/// Frequent English words that fuzzy name-matching must never touch.
/// This is a safety guard, not a dictionary: it only needs to cover words
/// likely to appear in conversational speech that could phonetically
/// collide with a name ("is a" vs Isa, "sure" vs Suren).
/// Explicit aliases bypass this list — if the user says "warren means Warren",
/// we believe them.
enum CommonWords {
    static func contains(_ lowercasedWord: String) -> Bool {
        words.contains(lowercasedWord)
    }

    private static let words: Set<String> = [
        // contractions (tokens keep their apostrophes)
        "i'm", "i've", "i'll", "i'd", "you're", "you've", "you'll", "you'd",
        "we're", "we've", "we'll", "we'd", "they're", "they've", "they'll",
        "they'd", "he's", "he'll", "he'd", "she's", "she'll", "she'd", "it's",
        "it'll", "that's", "that'll", "there's", "here's", "what's", "who's",
        "where's", "when's", "how's", "why's", "let's", "don't", "doesn't",
        "didn't", "can't", "couldn't", "won't", "wouldn't", "shouldn't",
        "isn't", "aren't", "wasn't", "weren't", "hasn't", "haven't", "hadn't",
        "mustn't", "needn't", "ain't", "y'all", "gonna", "wanna", "gotta",
        "kinda", "sorta", "cause", "'cause",
        // function words
        "a", "an", "the", "and", "or", "but", "nor", "so", "yet", "for", "of",
        "in", "on", "at", "by", "to", "up", "off", "out", "over", "under",
        "into", "onto", "with", "without", "within", "about", "above", "below",
        "across", "after", "before", "again", "against", "along", "among",
        "around", "as", "because", "between", "beyond", "during", "except",
        "from", "if", "like", "near", "since", "than", "through", "till",
        "toward", "towards", "until", "upon", "via", "while", "whilst",
        // pronouns & determiners
        "i", "me", "my", "mine", "myself", "we", "us", "our", "ours",
        "ourselves", "you", "your", "yours", "yourself", "yourselves", "he",
        "him", "his", "himself", "she", "her", "hers", "herself", "it", "its",
        "itself", "they", "them", "their", "theirs", "themselves", "this",
        "that", "these", "those", "who", "whom", "whose", "which", "what",
        "whatever", "whoever", "each", "every", "either", "neither", "some",
        "any", "no", "none", "all", "both", "few", "many", "much", "more",
        "most", "other", "another", "such", "own", "same", "several",
        // verbs (high frequency, incl. irregular forms)
        "am", "is", "are", "was", "were", "be", "been", "being", "have", "has",
        "had", "having", "do", "does", "did", "doing", "done", "will", "would",
        "shall", "should", "can", "could", "may", "might", "must", "ought",
        "need", "dare", "go", "goes", "went", "gone", "going", "get", "gets",
        "got", "gotten", "getting", "make", "makes", "made", "making", "know",
        "knows", "knew", "known", "knowing", "think", "thinks", "thought",
        "thinking", "take", "takes", "took", "taken", "taking", "see", "sees",
        "saw", "seen", "seeing", "come", "comes", "came", "coming", "want",
        "wants", "wanted", "wanting", "look", "looks", "looked", "looking",
        "use", "uses", "used", "using", "find", "finds", "found", "finding",
        "give", "gives", "gave", "given", "giving", "tell", "tells", "told",
        "telling", "work", "works", "worked", "working", "call", "calls",
        "called", "calling", "try", "tries", "tried", "trying", "ask", "asks",
        "asked", "asking", "feel", "feels", "felt", "feeling", "seem", "seems",
        "seemed", "leave", "leaves", "left", "leaving", "put", "puts",
        "putting", "mean", "means", "meant", "keep", "keeps", "kept", "let",
        "lets", "begin", "begins", "began", "begun", "show", "shows", "showed",
        "shown", "hear", "hears", "heard", "play", "plays", "played", "run",
        "runs", "ran", "move", "moves", "moved", "live", "lives", "lived",
        "believe", "bring", "brought", "happen", "happens", "happened",
        "write", "writes", "wrote", "written", "sit", "sits", "sat", "stand",
        "stands", "stood", "lose", "loses", "lost", "pay", "pays", "paid",
        "meet", "meets", "met", "include", "includes", "included", "continue",
        "set", "sets", "learn", "learns", "learned", "change", "changes",
        "changed", "lead", "leads", "led", "understand", "understood", "watch",
        "watches", "watched", "follow", "follows", "followed", "stop", "stops",
        "stopped", "create", "creates", "created", "speak", "speaks", "spoke",
        "spoken", "read", "reads", "spend", "spends", "spent", "grow", "grows",
        "grew", "grown", "open", "opens", "opened", "walk", "walks", "walked",
        "win", "wins", "won", "offer", "offers", "offered", "remember",
        "remembers", "remembered", "love", "loves", "loved", "consider",
        "appear", "appears", "appeared", "buy", "buys", "bought", "wait",
        "waits", "waited", "serve", "serves", "served", "die", "dies", "died",
        "send", "sends", "sent", "expect", "expects", "expected", "build",
        "builds", "built", "stay", "stays", "stayed", "fall", "falls", "fell",
        "fallen", "cut", "cuts", "reach", "reached", "kill", "remain", "say",
        "says", "said", "saying", "talk", "talks", "talked", "talking",
        "turn", "turns", "turned", "start", "starts", "started", "help",
        "helps", "helped", "sure", "surely",
        // common nouns & adjectives that collide with name shapes
        "time", "year", "years", "people", "way", "ways", "day", "days",
        "man", "men", "woman", "women", "thing", "things", "life", "child",
        "children", "world", "school", "state", "family", "student", "group",
        "country", "problem", "hand", "hands", "part", "parts", "place",
        "places", "case", "cases", "week", "weeks", "company", "system",
        "program", "question", "questions", "government", "number", "night",
        "nights", "point", "points", "home", "water", "room", "rooms",
        "mother", "father", "area", "money", "story", "stories", "fact",
        "facts", "month", "months", "lot", "lots", "right", "rights", "study",
        "book", "books", "eye", "eyes", "job", "jobs", "word", "words",
        "business", "issue", "issues", "side", "sides", "kind", "kinds",
        "head", "heads", "house", "houses", "service", "friend", "friends",
        "power", "hour", "hours", "game", "games", "line", "lines", "end",
        "ends", "member", "members", "law", "car", "cars", "city", "cities",
        "name", "names", "team", "teams", "minute", "minutes", "idea",
        "ideas", "kid", "kids", "body", "back", "backs", "parent", "parents",
        "face", "faces", "others", "level", "levels", "office", "door",
        "doors", "health", "person", "art", "war", "history", "party", "type",
        "types", "music", "food", "moment", "moments", "air", "teacher",
        "force", "education", "foot", "feet", "boy", "boys", "girl", "girls",
        "age", "ages", "policy", "process", "sense", "senses", "nation",
        "plan", "plans", "college", "interest", "death", "course", "someone",
        "something", "anything", "everything", "nothing", "everyone",
        "anyone", "nobody", "somebody", "everybody", "good", "new", "first",
        "last", "long", "great", "little", "old", "big", "high", "different",
        "small", "large", "next", "early", "young", "important", "public",
        "bad", "able", "best", "better", "sorry", "true", "whole", "real",
        "certain", "clear", "close", "cold", "warm", "dark", "deep", "easy",
        "hard", "fine", "free", "full", "happy", "sad", "late", "least",
        "less", "low", "main", "major", "only", "past", "poor", "rich",
        "ready", "recent", "short", "simple", "single", "strong", "wrong",
        "very", "too", "also", "just", "now", "then", "there", "here",
        "when", "where", "why", "how", "not", "never", "always", "often",
        "sometimes", "usually", "really", "still", "even", "well", "back",
        "away", "down", "today", "tomorrow", "yesterday", "yes", "maybe",
        "okay", "oh", "ah", "um", "uh", "yeah", "hey", "please", "thanks",
        "thank", "actually", "probably", "definitely", "basically",
        "literally", "honestly", "obviously", "totally", "pretty", "quite",
        "rather", "almost", "already", "enough", "else", "ever", "far",
        "once", "twice", "together", "instead", "perhaps", "though",
        "although", "however", "therefore", "meanwhile", "anyway", "besides",
        "soon", "later", "ago", "yet",
    ]
}
